name: UnitTest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.19, 1.20, 1.21]
    steps:
      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Setup Go Tools
        run: |
          make tools

      - name: Run Test
        run: |
          make vet
          make fmt-check
          make misspell-check
          make test

      - name: Codecov Report
        uses: codecov/codecov-action@v2
